#!/usr/bin/env bash
# Generates a branded HTML incident report from findings.json (deterministic, no AI/network).
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
. "$HERE/fos-common.sh"

FINDINGS="${1:?findings.json required}"
CASEDIR="${2:?case dir required}"
BRAND="${3:-First-On-Scene}"

VERDICT="$("$JQ" -r '.verdict' "$FINDINGS")"
case "$VERDICT" in ALL_CLEAR) VC="#16a34a";; MONITOR) VC="#d97706";; *) VC="#dc2626";; esac
HOST="$("$JQ" -r '.targetHostname' "$FINDINGS")"
TS="$(date -u +%Y%m%d_%H%M%S)"
REPORT="$CASEDIR/Incident_Report_${HOST}_${TS}.html"

MAN="$(fos_manifest_verify "$CASEDIR" 2>/dev/null | tail -n1 || true)"
if [ -z "$MAN" ]; then MAN="pending (sealed at case close)"; fi
COCV="$(fos_coc_verify "$CASEDIR" 2>/dev/null | tail -n1 || true)"
if [ -z "$COCV" ]; then COCV="pending"; fi

ROWS="$("$JQ" -r '
  def sevcolor: {info:"#6b7280",low:"#2563eb",medium:"#d97706",high:"#ea580c",critical:"#dc2626"}[.];
  .findings | sort_by(-.weight)[] |
  "<tr><td><code>\(.ruleId)</code></td><td>\(.name)<div class=note>\(.rationale)</div></td><td>\(.category)</td>" +
  "<td><span class=pill style=\"background:\(.severity|sevcolor)\">\(.severity)</span></td>" +
  "<td style=text-align:center>\(.weight)</td><td style=text-align:center>\(.evidenceCount)</td>" +
  "<td><code>\(.mitre.technique // "-")</code></td></tr>" +
  "<tr class=ev><td></td><td colspan=6><details><summary>Evidence &amp; FP guidance</summary><div class=note><b>FP:</b> \(.falsePositive)</div><pre>\(.evidence|tojson)</pre></details></td></tr>"
' "$FINDINGS")"
[ -z "$ROWS" ] && ROWS="<tr><td colspan=7 style=\"text-align:center;color:#16a34a\">No detections fired.</td></tr>"

AISECTION=""
if [ "$("$JQ" -r '.aiNarrative.enabled // false' "$FINDINGS")" = "true" ]; then
  AITEXT="$("$JQ" -r '.aiNarrative.text' "$FINDINGS")"
  AIMODEL="$("$JQ" -r '.aiNarrative.model' "$FINDINGS")"
  AISECTION="<div class=card><h2>Analyst Narrative <span class=note>(local AI: ${AIMODEL} - advisory only)</span></h2><p>${AITEXT}</p></div>"
fi

cat > "$REPORT" <<HTML
<!DOCTYPE html><html lang=en><head><meta charset=utf-8><title>${BRAND} Incident Report</title>
<style>
body{font-family:Segoe UI,Arial,sans-serif;margin:0;background:#f3f4f6;color:#111827}
header{background:#0f172a;color:#fff;padding:18px 28px}header h1{font-size:18px;margin:0}
.wrap{max-width:1100px;margin:22px auto;padding:0 18px}
.card{background:#fff;border:1px solid #e5e7eb;border-radius:10px;padding:18px 22px;margin-bottom:18px}
.verdict{font-size:26px;font-weight:700;color:${VC}}
table{width:100%;border-collapse:collapse;font-size:13px}
th,td{padding:8px 10px;border-bottom:1px solid #eef0f3;text-align:left;vertical-align:top}
th{background:#f9fafb;font-size:11px;text-transform:uppercase;color:#6b7280}
.pill{color:#fff;padding:2px 9px;border-radius:999px;font-size:11px;text-transform:uppercase}
.note{color:#6b7280;font-size:12px;margin-top:3px}
code{background:#f1f5f9;padding:1px 5px;border-radius:4px;font-size:12px}
pre{background:#0f172a;color:#e2e8f0;padding:10px;border-radius:6px;overflow:auto;font-size:11px}
.kv{display:grid;grid-template-columns:200px 1fr;gap:6px 16px;font-size:14px}
footer{text-align:center;color:#9ca3af;font-size:12px;padding:20px}
</style></head><body>
<header><h1>${BRAND} &middot; Incident Triage Report</h1></header>
<div class=wrap>
  <div class=card>
    <div class=verdict>${VERDICT}</div>
    <div class=kv>
      <b>Case ID</b><span>$("$JQ" -r '.caseId' "$FINDINGS")</span>
      <b>Host</b><span>${HOST}</span>
      <b>Classification</b><span>$("$JQ" -r '.classification' "$FINDINGS")</span>
      <b>Severity</b><span>$("$JQ" -r '.severity' "$FINDINGS")</span>
      <b>Score</b><span>$("$JQ" -r '.score' "$FINDINGS")</span>
      <b>Reason Code</b><span><code>$("$JQ" -r '.reasonCode' "$FINDINGS")</code></span>
      <b>Analyzed (UTC)</b><span>$("$JQ" -r '.analyzedTimestampUtc' "$FINDINGS")</span>
    </div>
  </div>
  <div class=card><h2>Evidence Integrity</h2><div class=kv>
    <b>Manifest (SHA-256)</b><span>${MAN}</span>
    <b>Chain of Custody</b><span>${COCV}</span>
  </div><div class=note>Produced with zero network egress.</div></div>
  ${AISECTION}
  <div class=card><h2>Detections ($("$JQ" -r '.findings|length' "$FINDINGS"))</h2>
    <table><tr><th>Rule</th><th>Finding</th><th>Category</th><th>Severity</th><th>Wt</th><th>Hits</th><th>MITRE</th></tr>
    ${ROWS}</table></div>
</div>
<footer>Generated by ${BRAND} (open source, CJIS-aligned). Deterministic engine - AI is advisory only.</footer>
</body></html>
HTML

fos_coc_add "$CASEDIR" "REPORT_GENERATED" "$(basename "$REPORT")" "$REPORT" >/dev/null
fos_log OK "Report written: $REPORT" "$CASEDIR"
echo "$REPORT"
