<#
.SYNOPSIS
    First-On-Scene - SINGLE-FILE incident triage for a possibly-compromised Windows host.
.DESCRIPTION
    Self-contained. No dependencies, no internet, no other files required. Paste it into a
    NinjaOne / ScreenConnect / RMM run-command window (or run locally), and it will:
      * collect volatile + persistent forensic artifacts (READ-ONLY),
      * inventory remote-access / RMM tools and flag any you did NOT authorize,
      * decide a deterministic verdict (ALL CLEAR / MONITOR / PROBLEM DETECTED),
      * seal the evidence (SHA-256 manifest + tamper-evident chain of custody),
      * print a clear verdict to the console and write an HTML report.

    Tell it which remote-access tools are EXPECTED so it only flags the rest:
        Invoke-FosTriage.ps1 -ExpectedRemoteTools 'NinjaOne,ScreenConnect'

    Exit codes (for RMM): 0 ALL_CLEAR | 10 MONITOR | 20 PROBLEM (Incident) | 21 PROBLEM (Breach) | 1 error
.NOTES
    Engine logic mirrors the modular scripts; the embedded ruleset is generated from
    rules/detections.json by tools/Build-Standalone.ps1. Run as Administrator for full coverage.
#>
[CmdletBinding()]
param(
    [string]$ExpectedRemoteTools = '',
    [string]$CaseDir,
    [string]$BrandName = 'First-On-Scene',
    [datetime]$StartTime,
    [datetime]$EndTime,
    [int]$MaxEvents = 1000,
    [switch]$Deep,
    [switch]$Quiet
)
$ErrorActionPreference = 'Stop'
$FosVersion = '3.3.0'

# RULES-BEGIN (generated by tools/Build-Standalone.ps1 from rules/detections.json - do not edit by hand)
$RULES_JSON = @'
{
  "rulesetVersion": "1.0.0",
  "description": "First-On-Scene deterministic detection ruleset. Each rule maps to a MITRE ATT&CK technique. The analyzer evaluates these generically against an artifact bundle. Authoring guide: docs/RULES.md.",
  "scoring": {
    "thresholds": { "monitor": 10, "problem": 30, "breach": 60 },
    "notes": "verdict = ALL_CLEAR (<monitor) | MONITOR (>=monitor, <problem) | PROBLEM_DETECTED (>=problem). classification escalates to Breach at >=breach OR when any matched rule sets escalateToBreach=true."
  },
  "conditionOperators": [
    "regexI", "notRegexI", "containsI", "notContainsI",
    "eq", "ne", "gt", "lt", "ge", "le", "in", "notIn", "exists", "isTrue", "isFalse"
  ],
  "rules": [
    {
      "id": "FOS-PER-001",
      "name": "Registry Run key launching from a non-system path",
      "category": "Persistence",
      "mitre": { "tactic": "TA0003", "technique": "T1547.001" },
      "type": "match",
      "selector": "artifacts.persistence.registryRunKeys",
      "match": "all",
      "severity": "low",
      "weight": 2,
      "reasonCode": "PERSISTENCE_RUN_KEY",
      "conditions": [
        { "field": "valueData", "op": "notRegexI", "value": "\\\\(Windows|Program Files|Program Files \\(x86\\))\\\\" },
        { "field": "valueData", "op": "regexI", "value": "\\.(exe|dll|bat|cmd|ps1|vbs|js|scr|jar|hta)" }
      ],
      "rationale": "Autorun entries that execute binaries from user, temp, or AppData paths are a classic persistence mechanism.",
      "falsePositive": "Some legitimate per-user apps (updaters, sync clients) register Run keys under AppData. Confirm the publisher and signature of the target binary."
    },
    {
      "id": "FOS-PER-002",
      "name": "Scheduled task executing from a user/temp path",
      "category": "Persistence",
      "mitre": { "tactic": "TA0003", "technique": "T1053.005" },
      "type": "match",
      "selector": "artifacts.persistence.scheduledTasks",
      "match": "all",
      "severity": "medium",
      "weight": 3,
      "reasonCode": "PERSISTENCE_SCHEDULED_TASK",
      "conditions": [
        { "field": "actions", "op": "regexI", "value": "\\\\(Users|Temp|AppData|ProgramData)\\\\" },
        { "field": "author", "op": "notRegexI", "value": "Microsoft" }
      ],
      "rationale": "Scheduled tasks pointing at user-writable directories and not authored by Microsoft are frequently used for persistence and re-infection.",
      "falsePositive": "Line-of-business apps and some installers create user-scoped tasks. Validate the action target and signing."
    },
    {
      "id": "FOS-PER-003",
      "name": "Auto-start service from a non-standard path",
      "category": "Persistence",
      "mitre": { "tactic": "TA0003", "technique": "T1543.003" },
      "type": "match",
      "selector": "artifacts.persistence.services",
      "match": "all",
      "severity": "medium",
      "weight": 4,
      "reasonCode": "PERSISTENCE_SERVICE",
      "conditions": [
        { "field": "startMode", "op": "regexI", "value": "auto" },
        { "field": "pathName", "op": "notRegexI", "value": "\\\\(Windows|Program Files|Program Files \\(x86\\))\\\\" },
        { "field": "pathName", "op": "regexI", "value": "\\.exe" }
      ],
      "rationale": "Auto-start services running executables outside Windows/Program Files are a high-confidence persistence indicator.",
      "falsePositive": "A few third-party agents install under ProgramData or custom roots. Verify the vendor."
    },
    {
      "id": "FOS-PER-004",
      "name": "WMI permanent event subscription present",
      "category": "Persistence",
      "mitre": { "tactic": "TA0003", "technique": "T1546.003" },
      "type": "builtin",
      "selector": "artifacts.persistence.wmiEventSubscriptions",
      "severity": "high",
      "weight": 10,
      "reasonCode": "PERSISTENCE_WMI",
      "rationale": "WMI permanent event subscriptions are a fileless persistence technique rarely used by legitimate software.",
      "falsePositive": "A small number of management/EDR products register WMI consumers. Enumerate the consumer command lines."
    },
    {
      "id": "FOS-EXE-001",
      "name": "Process running from a user/temp directory",
      "category": "Execution",
      "mitre": { "tactic": "TA0002", "technique": "T1059" },
      "type": "match",
      "selector": "artifacts.execution.processes",
      "match": "all",
      "severity": "low",
      "weight": 2,
      "reasonCode": "SUSPICIOUS_EXECUTION",
      "conditions": [
        { "field": "executablePath", "op": "regexI", "value": "\\\\(Temp|AppData\\\\Local\\\\Temp|ProgramData\\\\Temp)\\\\" }
      ],
      "rationale": "Executables launched from temporary directories are a common malware staging pattern.",
      "falsePositive": "Installers and self-updating apps frequently execute from Temp. Correlate with signing, parent process, and network activity."
    },
    {
      "id": "FOS-EXE-002",
      "name": "LOLBin spawned from Office or script host",
      "category": "Execution",
      "mitre": { "tactic": "TA0002", "technique": "T1059.001" },
      "type": "match",
      "selector": "artifacts.execution.processCreationEvents",
      "match": "all",
      "severity": "high",
      "weight": 7,
      "reasonCode": "SUSPICIOUS_PROCESS_TREE",
      "conditions": [
        { "field": "parentProcessName", "op": "regexI", "value": "(winword|excel|powerpnt|outlook|wscript|cscript|mshta)\\.exe" },
        { "field": "newProcessName", "op": "regexI", "value": "(powershell|cmd|rundll32|regsvr32|certutil|bitsadmin|curl|wmic)\\.exe" }
      ],
      "rationale": "Office or scripting hosts spawning living-off-the-land binaries is a hallmark of phishing-delivered execution.",
      "falsePositive": "Rare in normal use; investigate every hit."
    },
    {
      "id": "FOS-NET-001",
      "name": "Established connection to external host on a high-risk port",
      "category": "Command and Control",
      "mitre": { "tactic": "TA0011", "technique": "T1571" },
      "type": "match",
      "selector": "artifacts.network.connections",
      "match": "all",
      "severity": "high",
      "weight": 8,
      "reasonCode": "SUSPICIOUS_C2_CONNECTION",
      "conditions": [
        { "field": "remotePort", "op": "in", "value": [4444, 5555, 1080, 1337, 3333, 6667, 6697, 8443, 9001, 50050] },
        { "field": "state", "op": "regexI", "value": "established" },
        { "field": "remoteAddress", "op": "notRegexI", "value": "^(127\\.|10\\.|192\\.168\\.|172\\.(1[6-9]|2[0-9]|3[0-1])\\.|169\\.254\\.|0\\.0\\.0\\.0|::1|fe80|\\[?::)" }
      ],
      "rationale": "Outbound sessions to public IPs on known C2/Metasploit/IRC ports strongly indicate command-and-control.",
      "falsePositive": "8443 is sometimes a legitimate management port. Resolve the remote IP and owning process."
    },
    {
      "id": "FOS-NET-002",
      "name": "External RDP/SMB exposure (lateral movement surface)",
      "category": "Lateral Movement",
      "mitre": { "tactic": "TA0008", "technique": "T1021" },
      "type": "match",
      "selector": "artifacts.network.connections",
      "match": "all",
      "severity": "medium",
      "weight": 4,
      "reasonCode": "EXTERNAL_RDP_SMB",
      "conditions": [
        { "field": "remotePort", "op": "in", "value": [3389, 445] },
        { "field": "state", "op": "regexI", "value": "established" },
        { "field": "remoteAddress", "op": "notRegexI", "value": "^(127\\.|10\\.|192\\.168\\.|172\\.(1[6-9]|2[0-9]|3[0-1])\\.|169\\.254\\.|::1|fe80)" }
      ],
      "rationale": "RDP or SMB sessions to/from public addresses indicate either exposure or active lateral movement.",
      "falsePositive": "Site-to-site VPNs and cloud-hosted servers can produce legitimate external RDP/SMB."
    },
    {
      "id": "FOS-PSH-001",
      "name": "PowerShell download cradle / in-memory execution",
      "category": "Defense Evasion",
      "mitre": { "tactic": "TA0005", "technique": "T1059.001" },
      "type": "match",
      "selector": "artifacts.powerShellActivity.scriptBlockLogs",
      "match": "any",
      "severity": "high",
      "weight": 8,
      "reasonCode": "MALICIOUS_POWERSHELL",
      "conditions": [
        { "field": "scriptBlock", "op": "regexI", "value": "(downloadstring|downloadfile|net\\.webclient|iex\\s*\\(|invoke-expression|\\[reflection\\.assembly\\]::load|start-bitstransfer\\s+-source\\s+http|certutil\\s+-urlcache)" }
      ],
      "rationale": "Download cradles and in-memory code execution (IEX + Net.WebClient.DownloadString, reflective assembly loads) are high-confidence indicators of malicious PowerShell.",
      "falsePositive": "A few legitimate bootstrap/installer scripts use Invoke-Expression. Read the full script block for the URL and intent."
    },
    {
      "id": "FOS-PSH-002",
      "name": "Encoded PowerShell command",
      "category": "Defense Evasion",
      "mitre": { "tactic": "TA0005", "technique": "T1027" },
      "type": "match",
      "selector": "artifacts.powerShellActivity.scriptBlockLogs",
      "match": "any",
      "severity": "low",
      "weight": 2,
      "reasonCode": "ENCODED_POWERSHELL",
      "conditions": [
        { "field": "scriptBlock", "op": "regexI", "value": "(frombase64string|-enc\\b|-encodedcommand\\b)" }
      ],
      "rationale": "Base64/encoded PowerShell can hide intent. Low weight on its own because legitimate RMM and automation tooling (including NinjaOne) routinely use -EncodedCommand.",
      "falsePositive": "Very common in RMM/automation. Treat as corroborating context, not a standalone indicator."
    },
    {
      "id": "FOS-CRD-001",
      "name": "Privileged logon correlated with service logon",
      "category": "Credential Access",
      "mitre": { "tactic": "TA0006", "technique": "T1078" },
      "type": "builtin",
      "selector": "artifacts.credentialAccess",
      "severity": "medium",
      "weight": 5,
      "reasonCode": "SUSPICIOUS_PRIVILEGED_LOGON",
      "rationale": "Co-occurrence of special-privilege logons (4672) and service logons (4624 type 5) can indicate token abuse or malicious service installation.",
      "falsePositive": "Normal on busy servers. Treat as corroborating, not standalone, evidence."
    },
    {
      "id": "FOS-CRD-002",
      "name": "New local user account created",
      "category": "Persistence",
      "mitre": { "tactic": "TA0003", "technique": "T1136.001" },
      "type": "match",
      "selector": "artifacts.credentialAccess.userCreationEvents",
      "match": "all",
      "severity": "medium",
      "weight": 6,
      "reasonCode": "NEW_ACCOUNT_CREATED",
      "conditions": [
        { "field": "eventId", "op": "eq", "value": 4720 }
      ],
      "rationale": "Account creation (4720) outside a known provisioning workflow is a persistence and backdoor indicator.",
      "falsePositive": "Legitimate onboarding/IT provisioning. Correlate with change tickets."
    },
    {
      "id": "FOS-AF-001",
      "name": "Timestomping (creation time later than last write)",
      "category": "Defense Evasion",
      "mitre": { "tactic": "TA0005", "technique": "T1070.006" },
      "type": "builtin",
      "selector": "artifacts.fileSystem.fileMetadata",
      "severity": "medium",
      "weight": 4,
      "reasonCode": "TIMESTOMPING",
      "rationale": "A creation timestamp later than the last-write timestamp is a strong anti-forensic timestomping indicator.",
      "falsePositive": "File copy/restore operations and some backup tools can legitimately reorder MACE times."
    },
    {
      "id": "FOS-AV-001",
      "name": "Windows Defender detected threats",
      "category": "Malware",
      "mitre": { "tactic": "TA0002", "technique": "T1204" },
      "type": "builtin",
      "selector": "artifacts.antivirusScans.defenderScan",
      "severity": "critical",
      "weight": 20,
      "escalateToBreach": false,
      "reasonCode": "MALWARE_DETECTED",
      "rationale": "An on-box AV engine confirming a detection is high-confidence evidence of malware.",
      "falsePositive": "PUA/heuristic detections occasionally over-report. Confirm the threat name."
    },
    {
      "id": "FOS-AV-002",
      "name": "ClamAV detected infected files",
      "category": "Malware",
      "mitre": { "tactic": "TA0002", "technique": "T1204" },
      "type": "builtin",
      "selector": "artifacts.antivirusScans.clamavScan",
      "severity": "critical",
      "weight": 18,
      "reasonCode": "MALWARE_DETECTED",
      "rationale": "ClamAV signature hits indicate known-malicious files present on disk.",
      "falsePositive": "ClamAV can flag cracked software and test files (EICAR). Verify the signature name."
    },
    {
      "id": "FOS-RAN-001",
      "name": "Ransom note filename indicator",
      "category": "Impact",
      "mitre": { "tactic": "TA0040", "technique": "T1486" },
      "type": "match",
      "selector": "artifacts.fileSystem.fileMetadata",
      "match": "any",
      "severity": "critical",
      "weight": 30,
      "escalateToBreach": true,
      "reasonCode": "RANSOMWARE_ENCRYPTED_FILES",
      "conditions": [
        { "field": "fileName", "op": "regexI", "value": "(readme|recover|restore|how.?to.?decrypt|decrypt.?instruction|_readme|@want_to_recover)\\.(txt|html|hta)$" }
      ],
      "rationale": "Ransom-note filenames in collected file metadata are a near-certain ransomware impact indicator.",
      "falsePositive": "A plain README.txt is benign; the regex targets recovery/decrypt phrasing. Confirm contents."
    },
    {
      "id": "FOS-NIX-001",
      "name": "Cron job invoking a download cradle or shell",
      "category": "Persistence",
      "mitre": { "tactic": "TA0003", "technique": "T1053.003" },
      "type": "match",
      "selector": "artifacts.persistence.cronJobs",
      "match": "any",
      "severity": "high",
      "weight": 7,
      "reasonCode": "PERSISTENCE_CRON",
      "conditions": [
        { "field": "command", "op": "regexI", "value": "(curl|wget).*(\\|\\s*(ba)?sh)|/tmp/|base64\\s+-d|python.*-c|nc\\s|/dev/tcp/" }
      ],
      "rationale": "Cron entries that fetch and pipe code to a shell, or run from /tmp, are a Linux persistence/backdoor pattern.",
      "falsePositive": "Some legitimate maintenance jobs use curl/wget. Review the full command."
    },
    {
      "id": "FOS-NIX-002",
      "name": "systemd service executing from a world-writable path",
      "category": "Persistence",
      "mitre": { "tactic": "TA0003", "technique": "T1543.002" },
      "type": "match",
      "selector": "artifacts.persistence.systemdServices",
      "match": "any",
      "severity": "high",
      "weight": 7,
      "reasonCode": "PERSISTENCE_SYSTEMD",
      "conditions": [
        { "field": "execStart", "op": "regexI", "value": "(/tmp/|/dev/shm/|/var/tmp/|/home/[^/]+/\\.)" }
      ],
      "rationale": "systemd units launching binaries from /tmp, /dev/shm, or hidden home paths are a strong Linux persistence indicator.",
      "falsePositive": "Uncommon for legitimate units. Investigate every hit."
    },
    {
      "id": "FOS-RAT-001",
      "name": "Remote-access / RMM tool present but not declared",
      "category": "Remote Access",
      "mitre": { "tactic": "TA0011", "technique": "T1219" },
      "type": "builtin",
      "selector": "artifacts.remoteAccess.tools",
      "severity": "info",
      "weight": 0,
      "reasonCode": "UNDECLARED_REMOTE_ACCESS",
      "rationale": "A remote-access or RMM agent is present that was not listed in -ExpectedRemoteTools. In an MSP context this is almost always one of your own sanctioned agents, so it is shown for review only and does NOT affect the verdict. Confirm each tool is yours; an agent you genuinely did not install (e.g. attacker-staged AnyDesk, TeamViewer, or RustDesk) is worth investigating.",
      "falsePositive": "Almost always a legitimate tool the MSP did not declare. List your sanctioned agents with -ExpectedRemoteTools (e.g. 'NinjaOne,ScreenConnect') to label them as expected."
    },
    {
      "id": "FOS-RAT-002",
      "name": "Expected remote-access tool present (context)",
      "category": "Remote Access",
      "mitre": { "tactic": "TA0011", "technique": "T1219" },
      "type": "builtin",
      "selector": "artifacts.remoteAccess.tools",
      "severity": "info",
      "weight": 0,
      "reasonCode": "EXPECTED_REMOTE_ACCESS",
      "rationale": "Sanctioned remote-access / RMM agents found on the host, shown for context. Does not affect the score.",
      "falsePositive": "Informational only."
    },
    {
      "id": "FOS-DEF-001",
      "name": "Microsoft Defender real-time protection is OFF",
      "category": "Defense Evasion",
      "mitre": { "tactic": "TA0005", "technique": "T1562.001" },
      "type": "builtin",
      "selector": "artifacts.securityPosture.defender",
      "severity": "critical",
      "weight": 14,
      "reasonCode": "AV_DISABLED",
      "rationale": "Disabled real-time AV protection on a suspected-compromise host is a top attacker action (impair defenses).",
      "falsePositive": "A third-party AV may legitimately suppress Defender. Confirm another AV product is active and managed."
    },
    {
      "id": "FOS-DEF-002",
      "name": "Defender exclusions are configured",
      "category": "Defense Evasion",
      "mitre": { "tactic": "TA0005", "technique": "T1562.001" },
      "type": "builtin",
      "selector": "artifacts.securityPosture.defender",
      "severity": "medium",
      "weight": 5,
      "reasonCode": "AV_EXCLUSIONS",
      "rationale": "Attackers add path/extension/process exclusions so their tooling is never scanned. Review every exclusion.",
      "falsePositive": "Many environments set legitimate exclusions (line-of-business apps, backup agents). Compare against your baseline."
    },
    {
      "id": "FOS-DEF-003",
      "name": "Defender tamper protection is OFF",
      "category": "Defense Evasion",
      "mitre": { "tactic": "TA0005", "technique": "T1562.001" },
      "type": "builtin",
      "selector": "artifacts.securityPosture.defender",
      "severity": "medium",
      "weight": 5,
      "reasonCode": "TAMPER_PROTECTION_OFF",
      "rationale": "Tamper protection off allows AV settings to be silently changed; a common pre-attack step.",
      "falsePositive": "Some management tooling disables it. Verify it is intentional and policy-managed."
    },
    {
      "id": "FOS-EXE-003",
      "name": "Unsigned executable running from a user/temp path",
      "category": "Execution",
      "mitre": { "tactic": "TA0005", "technique": "T1036" },
      "type": "match",
      "selector": "artifacts.execution.processes",
      "match": "all",
      "severity": "high",
      "weight": 6,
      "reasonCode": "UNSIGNED_BINARY",
      "conditions": [
        { "field": "executablePath", "op": "regexI", "value": "\\\\(Users|Temp|AppData|ProgramData)\\\\" },
        { "field": "signatureStatus", "op": "ne", "value": "Valid" },
        { "field": "executablePath", "op": "exists" }
      ],
      "rationale": "A process with no valid Authenticode signature running from a user-writable path is a strong malware indicator.",
      "falsePositive": "Some legitimate niche/in-house tools are unsigned. Check the SHA-256 against your tooling or an IOC source."
    },
    {
      "id": "FOS-EXE-004",
      "name": "Running process whose on-disk image was deleted",
      "category": "Defense Evasion",
      "mitre": { "tactic": "TA0005", "technique": "T1070.004" },
      "type": "match",
      "selector": "artifacts.execution.processes",
      "match": "all",
      "severity": "high",
      "weight": 9,
      "reasonCode": "DELETED_PROCESS_IMAGE",
      "conditions": [
        { "field": "imageDeleted", "op": "isTrue" }
      ],
      "rationale": "A process still running while its executable has been deleted from disk is a classic drop-execute-delete malware pattern.",
      "falsePositive": "Can occur right after a legitimate app self-update. Correlate with signing and network activity."
    },
    {
      "id": "FOS-EXE-005",
      "name": "Unsigned module loaded into a process (possible injection)",
      "category": "Defense Evasion",
      "mitre": { "tactic": "TA0005", "technique": "T1055" },
      "type": "match",
      "selector": "artifacts.execution.injectedModules",
      "match": "all",
      "severity": "high",
      "weight": 7,
      "reasonCode": "POSSIBLE_INJECTION",
      "conditions": [
        { "field": "signatureStatus", "op": "ne", "value": "Valid" }
      ],
      "rationale": "An unsigned DLL loaded from a user/temp path into another process can indicate DLL injection or side-loading (-Deep scan).",
      "falsePositive": "Some legitimate plugins are unsigned. Verify the module path and publisher."
    },
    {
      "id": "FOS-PER-005",
      "name": "Image File Execution Options debugger hijack",
      "category": "Persistence",
      "mitre": { "tactic": "TA0003", "technique": "T1546.012" },
      "type": "match",
      "selector": "artifacts.persistence.asep",
      "match": "all",
      "severity": "high",
      "weight": 9,
      "reasonCode": "IFEO_HIJACK",
      "conditions": [ { "field": "category", "op": "eq", "value": "IFEO" } ],
      "rationale": "An IFEO 'Debugger' value silently launches an attacker program whenever a target executable runs.",
      "falsePositive": "Legitimate debuggers/AV occasionally set IFEO. Inspect the debugger target."
    },
    {
      "id": "FOS-PER-006",
      "name": "AppInit_DLLs is populated",
      "category": "Persistence",
      "mitre": { "tactic": "TA0003", "technique": "T1546.010" },
      "type": "match",
      "selector": "artifacts.persistence.asep",
      "match": "all",
      "severity": "high",
      "weight": 8,
      "reasonCode": "APPINIT_DLL",
      "conditions": [ { "field": "category", "op": "eq", "value": "AppInitDLLs" } ],
      "rationale": "AppInit_DLLs are loaded into nearly every process; attackers use it for system-wide injection/persistence.",
      "falsePositive": "Rare in modern, well-managed systems. Investigate the listed DLL."
    },
    {
      "id": "FOS-PER-007",
      "name": "Winlogon Shell/Userinit modified",
      "category": "Persistence",
      "mitre": { "tactic": "TA0003", "technique": "T1547.004" },
      "type": "match",
      "selector": "artifacts.persistence.asep",
      "match": "all",
      "severity": "high",
      "weight": 9,
      "reasonCode": "WINLOGON_HIJACK",
      "conditions": [ { "field": "category", "op": "eq", "value": "Winlogon" } ],
      "rationale": "Winlogon Shell/Userinit deviating from defaults runs attacker code at every interactive logon.",
      "falsePositive": "Some legacy line-of-business shells customize these. Verify the value."
    },
    {
      "id": "FOS-PER-008",
      "name": "Accessibility binary hijack (sticky-keys backdoor)",
      "category": "Persistence",
      "mitre": { "tactic": "TA0003", "technique": "T1546.008" },
      "type": "match",
      "selector": "artifacts.persistence.asep",
      "match": "all",
      "severity": "critical",
      "weight": 12,
      "escalateToBreach": true,
      "reasonCode": "ACCESSIBILITY_BACKDOOR",
      "conditions": [ { "field": "category", "op": "eq", "value": "Accessibility" } ],
      "rationale": "An IFEO/debugger on sethc/utilman/osk (accessibility binaries) is a pre-auth backdoor reachable from the logon screen.",
      "falsePositive": "Essentially always malicious. Investigate immediately."
    },
    {
      "id": "FOS-AF-002",
      "name": "Security/audit log was cleared",
      "category": "Defense Evasion",
      "mitre": { "tactic": "TA0005", "technique": "T1070.001" },
      "type": "match",
      "selector": "artifacts.defenseEvasion.logClearEvents",
      "match": "all",
      "severity": "high",
      "weight": 8,
      "reasonCode": "LOG_CLEARED",
      "conditions": [ { "field": "eventId", "op": "in", "value": [1102, 104] } ],
      "rationale": "Clearing the Security or System event log (1102/104) is a deliberate anti-forensic act around the incident window.",
      "falsePositive": "Rare administratively. Correlate the clear time with other activity."
    }
  ]
}
'@
# RULES-END

# ----------------------------- helpers -----------------------------
function Fos-Utc { (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ss.fffZ") }
function Fos-Operator { [ordered]@{ user=("{0}\{1}" -f $env:USERDOMAIN,$env:USERNAME); host=$env:COMPUTERNAME; tool="First-On-Scene/$FosVersion" } }
function Fos-CaseId { $s=(Get-Date).ToUniversalTime().ToString("yyyyMMdd-HHmmss"); $r=-join((48..57)+(97..102)|Get-Random -Count 6|ForEach-Object{[char]$_}); "FOS-$s-$($env:COMPUTERNAME.ToUpper())-$r" }
function Fos-Sha256String([string]$t){ $h=[System.Security.Cryptography.SHA256]::Create(); try{($h.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($t))|ForEach-Object{$_.ToString("x2")}) -join ''}finally{$h.Dispose()} }
function Fos-Sha256File([string]$p){ if(-not(Test-Path -LiteralPath $p)){return $null}; (Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLower() }
function Fos-WriteJson($o,[string]$p){ $j=$o|ConvertTo-Json -Depth 12; [System.IO.File]::WriteAllText($p,$j,(New-Object System.Text.UTF8Encoding($false))) }
function Fos-WriteText([string]$t,[string]$p){ [System.IO.File]::WriteAllText($p,$t,(New-Object System.Text.UTF8Encoding($false))) }
function Fos-Log([string]$m,[string]$lvl='INFO'){ $line="[$(Fos-Utc)] [$lvl] $m"; if($script:CaseDir){Add-Content -LiteralPath (Join-Path $script:CaseDir 'Steps_Taken.txt') -Value $line -Encoding UTF8}; if(-not $Quiet){$c=switch($lvl){'ERROR'{'Red'}'WARN'{'Yellow'}'OK'{'Green'}'STEP'{'Cyan'}default{'Gray'}}; Write-Host $line -ForegroundColor $c} }
function Fos-CocAdd([string]$action,[string]$detail='',[object[]]$files=@()){
    $coc=Join-Path $script:CaseDir 'chain_of_custody.log'; $prev='GENESIS'; $seq=0
    if(Test-Path -LiteralPath $coc){ $ex=@(Get-Content $coc|Where-Object{$_.Trim()}); if($ex.Count){$l=$ex[-1]|ConvertFrom-Json; $prev=$l.entryHash; $seq=[int]$l.seq+1} }
    $op=Fos-Operator; $fh=@(); foreach($f in $files){ if($f -and (Test-Path -LiteralPath $f)){ $fh+=[ordered]@{path=(Split-Path $f -Leaf);sha256=(Fos-Sha256File $f)} } }
    $payload=[ordered]@{seq=$seq;timestampUtc=(Fos-Utc);operator=$op.user;host=$op.host;action=$action;detail=$detail;files=$fh;prevHash=$prev}
    $pj=$payload|ConvertTo-Json -Depth 8 -Compress; $payload['entryHash']=Fos-Sha256String ($prev+'|'+$pj)
    Add-Content -LiteralPath $coc -Value ($payload|ConvertTo-Json -Depth 8 -Compress) -Encoding UTF8
}
function Fos-ManifestNew([string]$caseId){
    $mp=Join-Path $script:CaseDir 'manifest.json'; $op=Fos-Operator
    $ex=@('manifest.json','chain_of_custody.log','Steps_Taken.txt')
    $files=Get-ChildItem -LiteralPath $script:CaseDir -File|Where-Object{$ex -notcontains $_.Name}
    $entries=foreach($f in $files){ [ordered]@{file=$f.Name;sizeBytes=$f.Length;sha256=(Fos-Sha256File $f.FullName)} }
    Fos-WriteJson ([ordered]@{caseId=$caseId;createdUtc=(Fos-Utc);operator=$op;engineVersion=$FosVersion;algorithm='SHA-256';files=@($entries)}) $mp
}

# ----------------------------- engine -----------------------------
$SeverityRank=@{info=0;low=1;medium=2;high=3;critical=4}
$MultCap=@{info=1;low=1;medium=2;high=3;critical=3}
function Resolve-FosPath($Root,[string]$Path){ $n=$Root; foreach($s in $Path.Split('.')){ if($null-eq $n){return $null}; $pr=$n.PSObject.Properties[$s]; if(-not $pr){return $null}; $n=$pr.Value }; $n }
function Test-FosCondition($Item,$Cond){
    $val=$null; $p=$Item.PSObject.Properties[$Cond.field]; if($p){$val=$p.Value}; $sval=if($null-ne $val){[string]$val}else{''}
    switch($Cond.op){
        'regexI'{return [regex]::IsMatch($sval,$Cond.value,'IgnoreCase')}
        'notRegexI'{return -not [regex]::IsMatch($sval,$Cond.value,'IgnoreCase')}
        'containsI'{return $sval.IndexOf([string]$Cond.value,[System.StringComparison]::OrdinalIgnoreCase)-ge 0}
        'notContainsI'{return $sval.IndexOf([string]$Cond.value,[System.StringComparison]::OrdinalIgnoreCase)-lt 0}
        'eq'{return ($sval -eq [string]$Cond.value)}; 'ne'{return ($sval -ne [string]$Cond.value)}
        'gt'{return ([double]$val -gt [double]$Cond.value)}; 'lt'{return ([double]$val -lt [double]$Cond.value)}
        'ge'{return ([double]$val -ge [double]$Cond.value)}; 'le'{return ([double]$val -le [double]$Cond.value)}
        'in'{return (@($Cond.value) -contains $val)}; 'notIn'{return (-not(@($Cond.value) -contains $val))}
        'exists'{return ($sval -ne '')}; 'isTrue'{return ($val -eq $true)}; 'isFalse'{return ($val -eq $false -or $null -eq $val)}
        default{return $false}
    }
}
function Test-FosItem($Item,$Rule){ $r=foreach($c in $Rule.conditions){Test-FosCondition $Item $c}; if($Rule.match -eq 'any'){return (@($r) -contains $true)}; return (-not(@($r) -contains $false)) }
function Invoke-FosBuiltin($Bundle,$Rule){
    switch($Rule.id){
        'FOS-PER-004'{ $w=Resolve-FosPath $Bundle 'artifacts.persistence.wmiEventSubscriptions'; if(-not $w){return @()}; $c=@($w.eventConsumers); if($c.Count -gt 0){return @([pscustomobject]@{consumerCount=$c.Count;consumers=$c})}; return @() }
        'FOS-CRD-001'{ $ca=Resolve-FosPath $Bundle 'artifacts.credentialAccess'; if(-not $ca){return @()}; $a=@($ca.privilegeEscalationEvents)+@($ca.logonEvents|Where-Object{$_.eventId -eq 4672}); $s=@($ca.logonEvents|Where-Object{$_.eventId -eq 4624 -and $_.logonType -eq 5}); if((@($a).Count -gt 0)-and(@($s).Count -gt 0)){return @([pscustomobject]@{privilegedLogons=@($a).Count;serviceLogons=@($s).Count})}; return @() }
        'FOS-AF-001'{ $fm=Resolve-FosPath $Bundle 'artifacts.fileSystem.fileMetadata'; $h=foreach($f in @($fm)){try{ if([datetime]::Parse($f.created) -gt [datetime]::Parse($f.modified)){$f} }catch{}}; return @($h) }
        'FOS-AV-001'{ $s=Resolve-FosPath $Bundle 'artifacts.antivirusScans.defenderScan'; if($s -and ([int]$s.threatsFound -gt 0)){return @([pscustomobject]@{scanner='Windows Defender';threatsFound=$s.threatsFound;threats=$s.threats})}; return @() }
        'FOS-AV-002'{ $s=Resolve-FosPath $Bundle 'artifacts.antivirusScans.clamavScan'; if($s -and ([int]$s.threatsFound -gt 0)){return @([pscustomobject]@{scanner='ClamAV';threats=$s.threats})}; return @() }
        'FOS-RAT-001'{ $t=@(Resolve-FosPath $Bundle 'artifacts.remoteAccess.tools'); return @($t|Where-Object{$_ -and ($_.authorized -eq $false)}) }
        'FOS-RAT-002'{ $t=@(Resolve-FosPath $Bundle 'artifacts.remoteAccess.tools'); return @($t|Where-Object{$_ -and ($_.authorized -eq $true)}) }
        'FOS-DEF-001'{ $d=Resolve-FosPath $Bundle 'artifacts.securityPosture.defender'; if($d -and ($d.available -eq $true) -and ($d.realTimeEnabled -eq $false)){return @([pscustomobject]@{realTimeEnabled=$false})}; return @() }
        'FOS-DEF-002'{ $d=Resolve-FosPath $Bundle 'artifacts.securityPosture.defender'; if(-not $d){return @()}; $ex=@($d.exclusionPaths)+@($d.exclusionExtensions)+@($d.exclusionProcesses); if(@($ex|Where-Object{$_}).Count -gt 0){return @([pscustomobject]@{paths=$d.exclusionPaths;extensions=$d.exclusionExtensions;processes=$d.exclusionProcesses})}; return @() }
        'FOS-DEF-003'{ $d=Resolve-FosPath $Bundle 'artifacts.securityPosture.defender'; if($d -and ($d.available -eq $true) -and ($d.tamperProtectionEnabled -eq $false)){return @([pscustomobject]@{tamperProtectionEnabled=$false})}; return @() }
        default{return @()}
    }
}

# ----------------------------- main -----------------------------
try {
    $caseId = Fos-CaseId
    if(-not $CaseDir){ $CaseDir = Join-Path $env:ProgramData "FirstOnScene\cases\$caseId" }
    $script:CaseDir = $CaseDir
    New-Item -ItemType Directory -Path $CaseDir -Force | Out-Null

    $isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    Fos-Log "First-On-Scene standalone $FosVersion | case $caseId | admin=$isAdmin" 'STEP'
    if(-not $isAdmin){ Fos-Log "Not elevated; some artifacts may be incomplete." 'WARN' }
    Fos-CocAdd 'COLLECT_START' "host=$env:COMPUTERNAME admin=$isAdmin"

    $errors = New-Object System.Collections.ArrayList
    function CErr($c,$m){ [void]$errors.Add([ordered]@{component=$c;message="$m";timestampUtc=(Fos-Utc)}); Fos-Log "[$c] $m" 'WARN' }
    $evtFilter=@{LogName='Security'}; if($StartTime){$evtFilter['StartTime']=$StartTime}; if($EndTime){$evtFilter['EndTime']=$EndTime}

    # registry run keys
    $runKeys=New-Object System.Collections.ArrayList
    try{ foreach($pp in @(@{h='HKLM';p='HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run'},@{h='HKLM';p='HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce'},@{h='HKLM';p='HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run'},@{h='HKCU';p='HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run'},@{h='HKCU';p='HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce'})){ if(Test-Path $pp.p){ $it=Get-ItemProperty $pp.p; foreach($pr in $it.PSObject.Properties){ if($pr.Name -notmatch '^PS'){[void]$runKeys.Add([ordered]@{hive=$pp.h;keyPath=$pp.p;valueName=$pr.Name;valueData=[string]$pr.Value})} } } } }catch{CErr 'registryRunKeys' $_.Exception.Message}

    # scheduled tasks
    $tasks=New-Object System.Collections.ArrayList
    try{ foreach($t in (Get-ScheduledTask -ErrorAction Stop)){ $act=($t.Actions|ForEach-Object{($_.Execute,$_.Arguments) -join ' '}) -join ' ; '; [void]$tasks.Add([ordered]@{taskName=$t.TaskName;path=$t.TaskPath;state=[string]$t.State;enabled=($t.Settings.Enabled -ne $false);author=[string]$t.Author;actions=$act;triggers=(($t.Triggers|ForEach-Object{$_.CimClass.CimClassName}) -join ',')}) } }catch{CErr 'scheduledTasks' $_.Exception.Message}

    # services
    $services=New-Object System.Collections.ArrayList
    try{ foreach($s in (Get-CimInstance Win32_Service -ErrorAction Stop)){ [void]$services.Add([ordered]@{name=$s.Name;displayName=$s.DisplayName;state=$s.State;startMode=$s.StartMode;pathName=$s.PathName}) } }catch{CErr 'services' $_.Exception.Message}

    # wmi subscriptions
    $wmi=[ordered]@{eventFilters=@();eventConsumers=@();filterBindings=@()}
    try{ $wmi.eventFilters=@(Get-CimInstance -Namespace root\subscription -ClassName __EventFilter -ErrorAction SilentlyContinue|Select-Object Name,Query); $wmi.eventConsumers=@(Get-CimInstance -Namespace root\subscription -ClassName CommandLineEventConsumer -ErrorAction SilentlyContinue|Select-Object Name,CommandLineTemplate); $wmi.eventConsumers+=@(Get-CimInstance -Namespace root\subscription -ClassName ActiveScriptEventConsumer -ErrorAction SilentlyContinue|Select-Object Name,ScriptText); $wmi.filterBindings=@(Get-CimInstance -Namespace root\subscription -ClassName __FilterToConsumerBinding -ErrorAction SilentlyContinue|Select-Object Filter,Consumer) }catch{CErr 'wmi' $_.Exception.Message}

    # processes
    $processes=New-Object System.Collections.ArrayList
    try{ foreach($p in (Get-CimInstance Win32_Process -ErrorAction Stop)){ [void]$processes.Add([ordered]@{processId=[int]$p.ProcessId;name=$p.Name;executablePath=[string]$p.ExecutablePath;commandLine=[string]$p.CommandLine;parentProcessId=[int]$p.ParentProcessId;user=''}) } }catch{CErr 'processes' $_.Exception.Message}

    # network
    $connections=New-Object System.Collections.ArrayList
    try{ $pm=@{}; Get-Process -ErrorAction SilentlyContinue|ForEach-Object{$pm[$_.Id]=$_.ProcessName}; foreach($c in (Get-NetTCPConnection -ErrorAction Stop)){ [void]$connections.Add([ordered]@{protocol='TCP';localAddress=$c.LocalAddress;localPort=[int]$c.LocalPort;remoteAddress=$c.RemoteAddress;remotePort=[int]$c.RemotePort;state=[string]$c.State;processId=[int]$c.OwningProcess;processName=[string]$pm[[int]$c.OwningProcess]}) } }catch{CErr 'connections' $_.Exception.Message}

    # security events
    $logonEvents=New-Object System.Collections.ArrayList; $userCreate=New-Object System.Collections.ArrayList; $svcInstall=New-Object System.Collections.ArrayList; $privEsc=New-Object System.Collections.ArrayList
    try{ $f=$evtFilter.Clone(); $f['Id']=@(4624,4672,4720,4697); foreach($e in (Get-WinEvent -FilterHashtable $f -MaxEvents $MaxEvents -ErrorAction Stop)){ $msg=($e.Message -split "`n"|Select-Object -First 6) -join ' '; $ts=$e.TimeCreated.ToUniversalTime().ToString('o'); switch($e.Id){ 4624{$lt=0;try{$lt=[int]$e.Properties[8].Value}catch{};[void]$logonEvents.Add([ordered]@{eventId=4624;timestamp=$ts;logonType=$lt;account='';sourceAddress='';message=$msg})}; 4672{[void]$privEsc.Add([ordered]@{eventId=4672;timestamp=$ts;user='';privileges=$msg});[void]$logonEvents.Add([ordered]@{eventId=4672;timestamp=$ts;logonType=0;account='';sourceAddress='';message=$msg})}; 4720{[void]$userCreate.Add([ordered]@{eventId=4720;timestamp=$ts;message=$msg})}; 4697{[void]$svcInstall.Add([ordered]@{eventId=4697;timestamp=$ts;message=$msg})} } } }catch{CErr 'securityEvents' $_.Exception.Message}

    # powershell script-block logs
    $psLogs=New-Object System.Collections.ArrayList
    try{ $f=@{LogName='Microsoft-Windows-PowerShell/Operational';Id=4104}; if($StartTime){$f['StartTime']=$StartTime}; if($EndTime){$f['EndTime']=$EndTime}; foreach($e in (Get-WinEvent -FilterHashtable $f -MaxEvents $MaxEvents -ErrorAction Stop)){ [void]$psLogs.Add([ordered]@{timestamp=$e.TimeCreated.ToUniversalTime().ToString('o');scriptBlock=$e.Message;path=''}) } }catch{CErr 'powerShellLogs' 'no script-block logs (channel may be disabled)'}

    # file metadata
    $fileMeta=New-Object System.Collections.ArrayList
    try{ foreach($dir in @("$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup","$env:ProgramData\Microsoft\Windows\Start Menu\Programs\Startup","$env:TEMP","$env:windir\Temp")){ if(Test-Path $dir){ Get-ChildItem -LiteralPath $dir -File -ErrorAction SilentlyContinue|Select-Object -First 200|ForEach-Object{ [void]$fileMeta.Add([ordered]@{fileName=$_.FullName;size=[int64]$_.Length;permissions='';modified=$_.LastWriteTimeUtc.ToString('o');accessed=$_.LastAccessTimeUtc.ToString('o');created=$_.CreationTimeUtc.ToString('o')}) } } } }catch{CErr 'fileMetadata' $_.Exception.Message}

    # defender existing detections (read-only)
    $defender=[ordered]@{executed=$false;threatsFound=0;threats=@()}
    try{ $th=@(Get-MpThreatDetection -ErrorAction SilentlyContinue); if($th.Count -gt 0){ $defender.executed=$true;$defender.threatsFound=$th.Count;$defender.threats=@($th|Select-Object -First 50|ForEach-Object{[ordered]@{name=[string]$_.ThreatID;file=[string]($_.Resources -join ';')}}) } else {$defender.executed=$true} }catch{CErr 'defender' 'Get-MpThreatDetection unavailable'}

    # remote-access / RMM inventory
    $RemoteToolDefs=@(
        @{tool='AnyDesk';rx='anydesk'},@{tool='TeamViewer';rx='teamviewer'},
        @{tool='ScreenConnect / ConnectWise Control';rx='screenconnect|connectwise.?control'},
        @{tool='ConnectWise Automate (LabTech)';rx='ltsvc|labtech|connectwise automate'},
        @{tool='NinjaOne (NinjaRMM)';rx='ninjarmm|ninjaone'},@{tool='Atera';rx='ateraagent|\batera\b'},
        @{tool='Splashtop';rx='splashtop|srservice|srmanager'},@{tool='RustDesk';rx='rustdesk'},
        @{tool='LogMeIn';rx='logmein'},@{tool='GoTo / GoToAssist';rx='gotoassist|gotoresolve|g2comm|logmeinrescue'},
        @{tool='VNC (Ultra/Tight/Real)';rx='winvnc|tvnserver|vncserver|uvnc|realvnc|tightvnc'},
        @{tool='Ammyy Admin';rx='ammyy|aa_v3'},@{tool='Remote Utilities';rx='rutserv|rfusclient|remote utilities'},
        @{tool='DWAgent';rx='dwagent'},@{tool='Supremo';rx='supremo'},@{tool='Action1';rx='action1'},
        @{tool='Syncro';rx='syncro|kabuto'},@{tool='Datto RMM';rx='cagservice|centrastage|datto rmm'},
        @{tool='Kaseya';rx='kaseya|agentmon'},@{tool='BeyondTrust / Bomgar';rx='bomgar|beyondtrust'},
        @{tool='Chrome Remote Desktop';rx='remoting_host|chrome remote desktop|chromoting'},
        @{tool='ToDesk';rx='todesk'},@{tool='Parsec';rx='\bparsec'},@{tool='Quick Assist / Remote Assistance';rx='quickassist|msra\.exe'}
    )
    $expectedTokens=@(); if($ExpectedRemoteTools){ $expectedTokens=$ExpectedRemoteTools -split '[,;]'|ForEach-Object{$_.Trim().ToLower()}|Where-Object{$_} }
    $remoteTools=New-Object System.Collections.ArrayList
    try{
        $installed=@(); foreach($p in @('HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*','HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*','HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*')){ $installed+=Get-ItemProperty $p -ErrorAction SilentlyContinue|Where-Object{$_.DisplayName}|Select-Object -ExpandProperty DisplayName }
        $procNames=@($processes|ForEach-Object{$_.name}); $svcText=@($services|ForEach-Object{"$($_.name) $($_.displayName) $($_.pathName)"})
        foreach($def in $RemoteToolDefs){ $ev=@(); if($procNames|Where-Object{$_ -match $def.rx}){$ev+='process'}; if($svcText|Where-Object{$_ -match $def.rx}){$ev+='service'}; $im=@($installed|Where-Object{$_ -match $def.rx}); if($im.Count -gt 0){$ev+='installed'}; if($ev.Count -gt 0){ $tl=$def.tool.ToLower(); $auth=$false; foreach($tok in $expectedTokens){if($tl -like "*$tok*"){$auth=$true;break}}; [void]$remoteTools.Add([ordered]@{tool=$def.tool;evidence=($ev -join ',');detail=([string]($im|Select-Object -First 1));authorized=$auth}) } }
    }catch{CErr 'remoteAccess' $_.Exception.Message}

    # security posture (Defender)
    $defenderPosture=[ordered]@{available=$false;realTimeEnabled=$null;antivirusEnabled=$null;tamperProtectionEnabled=$null;exclusionPaths=@();exclusionExtensions=@();exclusionProcesses=@()}
    try{ $st=Get-MpComputerStatus -ErrorAction Stop; $pf=Get-MpPreference -ErrorAction SilentlyContinue; $defenderPosture.available=$true; $defenderPosture.realTimeEnabled=[bool]$st.RealTimeProtectionEnabled; $defenderPosture.antivirusEnabled=[bool]$st.AntivirusEnabled; $defenderPosture.tamperProtectionEnabled=[bool]$st.IsTamperProtected; if($pf){$defenderPosture.exclusionPaths=@($pf.ExclusionPath|Where-Object{$_});$defenderPosture.exclusionExtensions=@($pf.ExclusionExtension|Where-Object{$_});$defenderPosture.exclusionProcesses=@($pf.ExclusionProcess|Where-Object{$_})} }catch{CErr 'securityPosture' 'Defender status unavailable'}

    # process signatures + hash + image-deleted
    try{ $sigCache=@{}; foreach($pr in $processes){ $path=[string]$pr.executablePath; $pr['signatureStatus']='';$pr['signer']='';$pr['sha256']='';$pr['imageDeleted']=$false; if($path -match '^[A-Za-z]:\\'){ if(Test-Path -LiteralPath $path){ if(-not $sigCache.ContainsKey($path)){ $s='';$signer='';$hash=''; try{$sig=Get-AuthenticodeSignature -LiteralPath $path -ErrorAction SilentlyContinue; if($sig){$s=[string]$sig.Status; if($sig.SignerCertificate){$signer=$sig.SignerCertificate.Subject}}}catch{}; try{$hash=(Get-FileHash -LiteralPath $path -Algorithm SHA256 -ErrorAction SilentlyContinue).Hash.ToLower()}catch{}; $sigCache[$path]=@{status=$s;signer=$signer;sha256=$hash} }; $pr['signatureStatus']=$sigCache[$path].status;$pr['signer']=$sigCache[$path].signer;$pr['sha256']=$sigCache[$path].sha256 } else {$pr['imageDeleted']=$true} } } }catch{CErr 'processSignatures' $_.Exception.Message}

    # ASEP hijacks (anomalies only)
    $asep=New-Object System.Collections.ArrayList
    try{ $ifeoRoot='HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options'; $accessib='sethc\.exe|utilman\.exe|osk\.exe|magnify\.exe|narrator\.exe|displayswitch\.exe|atbroker\.exe'
        if(Test-Path $ifeoRoot){ foreach($k in (Get-ChildItem $ifeoRoot -ErrorAction SilentlyContinue)){ $dbg=(Get-ItemProperty -Path $k.PSPath -Name Debugger -ErrorAction SilentlyContinue).Debugger; if($dbg){ $cat=if($k.PSChildName -match $accessib){'Accessibility'}else{'IFEO'}; [void]$asep.Add([ordered]@{category=$cat;location=$k.PSChildName;name='Debugger';value=[string]$dbg}) } } }
        foreach($w in @('HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows','HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\Windows')){ $ai=(Get-ItemProperty -Path $w -Name AppInit_DLLs -ErrorAction SilentlyContinue).AppInit_DLLs; if($ai -and $ai.Trim()){[void]$asep.Add([ordered]@{category='AppInitDLLs';location=$w;name='AppInit_DLLs';value=[string]$ai})} }
        $wl='HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'; $shell=(Get-ItemProperty -Path $wl -Name Shell -ErrorAction SilentlyContinue).Shell; $userinit=(Get-ItemProperty -Path $wl -Name Userinit -ErrorAction SilentlyContinue).Userinit
        if($shell -and $shell -notmatch '^explorer\.exe\s*$'){[void]$asep.Add([ordered]@{category='Winlogon';location=$wl;name='Shell';value=[string]$shell})}
        if($userinit -and $userinit -notmatch '(?i)^C:\\Windows\\system32\\userinit\.exe,?\s*$'){[void]$asep.Add([ordered]@{category='Winlogon';location=$wl;name='Userinit';value=[string]$userinit})}
    }catch{CErr 'asep' $_.Exception.Message}

    # access control posture
    $accessControl=[ordered]@{localAdmins=@();rdpEnabled=$null;shares=@()}
    try{ try{$accessControl.localAdmins=@(Get-LocalGroupMember -Group 'Administrators' -ErrorAction Stop|ForEach-Object{[string]$_.Name})}catch{$accessControl.localAdmins=@((net localgroup administrators) 2>$null|Where-Object{$_ -and $_ -notmatch '----|completed|^Members|^Alias|^Comment'})}; $deny=(Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server' -Name fDenyTSConnections -ErrorAction SilentlyContinue).fDenyTSConnections; $accessControl.rdpEnabled=($deny -eq 0); $accessControl.shares=@(Get-CimInstance Win32_Share -ErrorAction SilentlyContinue|Where-Object{$_.Name -notmatch '\$$'}|ForEach-Object{"$($_.Name) -> $($_.Path)"}) }catch{CErr 'accessControl' $_.Exception.Message}

    # log-clear events
    $logClear=New-Object System.Collections.ArrayList
    foreach($spec in @(@{log='Security';id=1102},@{log='System';id=104})){ $f=@{LogName=$spec.log;Id=$spec.id}; if($StartTime){$f['StartTime']=$StartTime}; if($EndTime){$f['EndTime']=$EndTime}; try{foreach($e in (Get-WinEvent -FilterHashtable $f -MaxEvents 20 -ErrorAction Stop)){[void]$logClear.Add([ordered]@{eventId=$spec.id;timestamp=$e.TimeCreated.ToUniversalTime().ToString('o');log=$spec.log;message=(($e.Message -split "`n"|Select-Object -First 2) -join ' ')})}}catch{} }

    # deep-mode: prefetch + injection modules
    $prefetch=New-Object System.Collections.ArrayList; $injectedModules=New-Object System.Collections.ArrayList
    if($Deep){
        try{ $pfDir="$env:windir\Prefetch"; if(Test-Path $pfDir){Get-ChildItem -LiteralPath $pfDir -Filter *.pf -ErrorAction SilentlyContinue|Sort-Object LastWriteTimeUtc -Descending|Select-Object -First 300|ForEach-Object{[void]$prefetch.Add([ordered]@{name=$_.Name;lastRunUtc=$_.LastWriteTimeUtc.ToString('o')})}} }catch{CErr 'prefetch' $_.Exception.Message}
        try{ $modCache=@{}; foreach($p in (Get-Process -ErrorAction SilentlyContinue)){ try{ foreach($m in $p.Modules){ $mp=$m.FileName; if($mp -match '\\(Users|Temp|AppData|ProgramData)\\'){ if(-not $modCache.ContainsKey($mp)){$stt='';try{$stt=[string](Get-AuthenticodeSignature -LiteralPath $mp -ErrorAction SilentlyContinue).Status}catch{};$modCache[$mp]=$stt}; if($modCache[$mp] -ne 'Valid'){[void]$injectedModules.Add([ordered]@{process=$p.ProcessName;module=$mp;signatureStatus=$modCache[$mp]})} } } }catch{} } }catch{CErr 'injectedModules' $_.Exception.Message}
    }

    # host / system info (context - never affects the verdict)
    $cs=$null
    $sysInfo=[ordered]@{}
    try{
        $cs=Get-CimInstance Win32_ComputerSystem -ErrorAction SilentlyContinue
        $bios=Get-CimInstance Win32_BIOS -ErrorAction SilentlyContinue
        $os=Get-CimInstance Win32_OperatingSystem -ErrorAction SilentlyContinue
        $cpu=@(Get-CimInstance Win32_Processor -ErrorAction SilentlyContinue)|Select-Object -First 1
        $lastBoot='';$uptime=''
        if($os -and $os.LastBootUpTime){ try{ $lb=$os.LastBootUpTime; $lastBoot=$lb.ToUniversalTime().ToString('o'); $sp=(Get-Date)-$lb; $uptime=('{0}d {1}h {2}m' -f $sp.Days,$sp.Hours,$sp.Minutes) }catch{} }
        $sysInfo=[ordered]@{
            manufacturer=[string]$cs.Manufacturer; model=[string]$cs.Model; serialNumber=[string]$bios.SerialNumber
            systemType=[string]$cs.SystemType; domain=[string]$cs.Domain; partOfDomain=[bool]$cs.PartOfDomain
            osCaption=[string]$os.Caption; osVersion=[string]$os.Version; osBuild=[string]$os.BuildNumber; osArchitecture=[string]$os.OSArchitecture
            cpu=[string]$cpu.Name; cpuCores=[int]$cpu.NumberOfCores; cpuLogical=[int]$cpu.NumberOfLogicalProcessors
            ramGB=$(if($cs.TotalPhysicalMemory){[math]::Round([double]$cs.TotalPhysicalMemory/1GB,1)}else{0}); lastBootUtc=$lastBoot; uptime=$uptime
        }
    }catch{CErr 'systemInfo' $_.Exception.Message}

    # fixed disks (capacity / free space)
    $disks=New-Object System.Collections.ArrayList
    try{ foreach($d in (Get-CimInstance Win32_LogicalDisk -Filter 'DriveType=3' -ErrorAction SilentlyContinue)){ $sz=[double]$d.Size; $fr=[double]$d.FreeSpace; [void]$disks.Add([ordered]@{drive=[string]$d.DeviceID;volumeName=[string]$d.VolumeName;sizeGB=[math]::Round($sz/1GB,1);freeGB=[math]::Round($fr/1GB,1);usedGB=[math]::Round(($sz-$fr)/1GB,1);percentFree=$(if($sz -gt 0){[math]::Round(($fr/$sz)*100,0)}else{0})}) } }catch{CErr 'disks' $_.Exception.Message}

    # logged-on interactive users
    $loggedOnUsers=New-Object System.Collections.ArrayList
    try{
        $seen=@{}
        foreach($e in (Get-CimInstance Win32_Process -Filter "Name='explorer.exe'" -ErrorAction SilentlyContinue)){
            try{ $o=Invoke-CimMethod -InputObject $e -MethodName GetOwner -ErrorAction SilentlyContinue
                if($o -and $o.User){ $u=("{0}\{1}" -f $o.Domain,$o.User).TrimStart('\'); $k=$u.ToLower(); if(-not $seen.ContainsKey($k)){$seen[$k]=$true;[void]$loggedOnUsers.Add([ordered]@{user=$u;session='interactive';source='explorer'})} } }catch{}
        }
        if($cs -and $cs.UserName){ $u=[string]$cs.UserName; $k=$u.ToLower(); if(-not $seen.ContainsKey($k)){$seen[$k]=$true;[void]$loggedOnUsers.Add([ordered]@{user=$u;session='console';source='ComputerSystem'})} }
    }catch{CErr 'loggedOnUsers' $_.Exception.Message}

    $bundle=[ordered]@{
        schemaVersion='3.0.0'
        metadata=[ordered]@{caseId=$caseId;collectionTimestampUtc=(Fos-Utc);targetHostname=$env:COMPUTERNAME;platform='windows';osVersion=(Get-CimInstance Win32_OperatingSystem -ErrorAction SilentlyContinue).Caption;collectorVersion=$FosVersion;executionMode='local';evidenceIntegrityMode=$true;expectedRemoteTools=@($expectedTokens);operator=(Fos-Operator);host=[ordered]@{system=$sysInfo;disks=@($disks);loggedOnUsers=@($loggedOnUsers)};errors=@($errors)}
        artifacts=[ordered]@{
            remoteAccess=[ordered]@{tools=@($remoteTools)}
            securityPosture=[ordered]@{defender=$defenderPosture}
            accessControl=$accessControl
            defenseEvasion=[ordered]@{logClearEvents=@($logClear)}
            persistence=[ordered]@{registryRunKeys=@($runKeys);scheduledTasks=@($tasks);services=@($services);wmiEventSubscriptions=$wmi;asep=@($asep)}
            execution=[ordered]@{processes=@($processes);processCreationEvents=@();prefetch=@($prefetch);injectedModules=@($injectedModules)}
            network=[ordered]@{connections=@($connections)}
            credentialAccess=[ordered]@{logonEvents=@($logonEvents);privilegeEscalationEvents=@($privEsc);userCreationEvents=@($userCreate);serviceInstallEvents=@($svcInstall)}
            fileSystem=[ordered]@{fileMetadata=@($fileMeta);browserArtifacts=@()}
            powerShellActivity=[ordered]@{scriptBlockLogs=@($psLogs)}
            antivirusScans=[ordered]@{defenderScan=$defender;clamavScan=[ordered]@{executed=$false;threatsFound=0;threats=@()}}
        }
    }
    $bundlePath=Join-Path $CaseDir 'bundle.json'; Fos-WriteJson $bundle $bundlePath
    Fos-CocAdd 'COLLECT_DONE' "proc=$($processes.Count) svc=$($services.Count) conn=$($connections.Count) remoteTools=$($remoteTools.Count)" @($bundlePath)
    Fos-Log "Collected. Analyzing..." 'STEP'

    # analyze
    $bundleObj=Get-Content $bundlePath -Raw|ConvertFrom-Json
    $ruleset=$RULES_JSON|ConvertFrom-Json; $thr=$ruleset.scoring.thresholds
    $findings=@()
    foreach($rule in $ruleset.rules){
        $ev=if($rule.type -eq 'builtin'){Invoke-FosBuiltin $bundleObj $rule}else{@(@(Resolve-FosPath $bundleObj $rule.selector)|Where-Object{$_ -and (Test-FosItem $_ $rule)})}
        if(@($ev).Count -gt 0){ $cnt=@($ev).Count; $findings+=[pscustomobject]@{ruleId=$rule.id;name=$rule.name;category=$rule.category;mitre=$rule.mitre;severity=$rule.severity;weight=[int]$rule.weight;rationale=$rule.rationale;falsePositive=$rule.falsePositive;reasonCode=$rule.reasonCode;escalate=[bool]$rule.escalateToBreach;evidenceCount=$cnt;evidence=@($ev|Select-Object -First 25)} }
    }
    $score=0; foreach($f in $findings){ $cap=$MultCap[$f.severity]; if(-not $cap){$cap=1}; $score+=($f.weight*[Math]::Min($f.evidenceCount,$cap)) }
    $verdict='ALL_CLEAR'; if($score -ge [int]$thr.problem){$verdict='PROBLEM_DETECTED'}elseif($score -ge [int]$thr.monitor){$verdict='MONITOR'}
    $isBreach=($score -ge [int]$thr.breach) -or (@($findings|Where-Object{$_.escalate}).Count -gt 0)
    switch($verdict){'ALL_CLEAR'{$classification='None';$exit=0}'MONITOR'{$classification='Event';$exit=10}'PROBLEM_DETECTED'{if($isBreach){$classification='Breach';$exit=21}else{$classification='Incident';$exit=20}}}
    $maxSev='info'; foreach($f in $findings){ if($SeverityRank[$f.severity] -gt $SeverityRank[$maxSev]){$maxSev=$f.severity} }
    $top=$findings|Sort-Object -Property @{Expression={$_.weight*[Math]::Min($_.evidenceCount,3)}} -Descending|Select-Object -First 1
    $reasonCode=if($top){$top.reasonCode}else{'NO_FINDINGS'}

    $result=[ordered]@{caseId=$caseId;analyzedTimestampUtc=(Fos-Utc);engineVersion=$FosVersion;rulesetVersion=$ruleset.rulesetVersion;targetHostname=$env:COMPUTERNAME;verdict=$verdict;score=$score;severity=$maxSev;classification=$classification;reasonCode=$reasonCode;thresholds=$thr;findings=@($findings)}
    $findingsPath=Join-Path $CaseDir 'findings.json'; Fos-WriteJson $result $findingsPath

    # HTML report
    $vc=switch($verdict){'ALL_CLEAR'{'#16a34a'}'MONITOR'{'#d97706'}default{'#dc2626'}}
    $sevColor=@{info='#6b7280';low='#2563eb';medium='#d97706';high='#ea580c';critical='#dc2626'}
    function HE($s){ if($null -eq $s){return ''}; [System.Net.WebUtility]::HtmlEncode([string]$s) }
    $rows=''
    foreach($d in ($findings|Sort-Object -Property @{Expression={$_.weight};Descending=$true})){ $clr=$sevColor[$d.severity]; $m=if($d.mitre){"$($d.mitre.technique)"}else{'-'}; $ej=HE(($d.evidence|ConvertTo-Json -Depth 6 -Compress)); if($ej.Length -gt 1000){$ej=$ej.Substring(0,1000)+' ...'}; $rows+="<tr><td><code>$(HE $d.ruleId)</code></td><td>$(HE $d.name)<div class=note>$(HE $d.rationale)</div></td><td><span class=pill style='background:$clr'>$(HE $d.severity)</span></td><td style=text-align:center>$($d.evidenceCount)</td><td><code>$(HE $m)</code></td></tr><tr><td></td><td colspan=4><details><summary>evidence</summary><pre>$ej</pre></details></td></tr>" }
    if(-not $rows){$rows="<tr><td colspan=5 style='text-align:center;color:#16a34a'>No detections fired.</td></tr>"}
    # Host card (system info + disks + logged-on users + remote-access tools, all informational)
    $hostCard=''
    $hi2=$bundle.metadata.host
    if($hi2){
        $si=$hi2.system
        $domTxt=if($si.partOfDomain){HE $si.domain}else{(HE $si.domain)+' (workgroup)'}
        $diskRows=''
        foreach($dk in @($hi2.disks)){ $pf=[double]$dk.percentFree; $dcol=if($pf -lt 10){'#dc2626'}elseif($pf -lt 20){'#d97706'}else{'#111827'}; $diskRows+="<tr><td><code>$(HE $dk.drive)</code> $(HE $dk.volumeName)</td><td>$($dk.sizeGB) GB</td><td>$($dk.freeGB) GB</td><td style='color:$dcol'>$($dk.percentFree)% free</td></tr>" }
        if(-not $diskRows){$diskRows="<tr><td colspan=4 style='color:#6b7280'>none</td></tr>"}
        $userList=(@($hi2.loggedOnUsers)|ForEach-Object{ (HE $_.user)+' <span class=note>('+(HE $_.session)+')</span>' }) -join ', '
        if(-not $userList){$userList='<span class=note>none detected</span>'}
        $rtools=@($bundle.artifacts.remoteAccess.tools)
        $rtxt=(@($rtools)|ForEach-Object{ $lab=if($_.authorized){'expected'}else{'undeclared'}; (HE $_.tool)+' <span class=note>('+$lab+')</span>' }) -join ', '
        if(-not $rtxt){$rtxt='<span class=note>none detected</span>'}
        $hostCard="<div class=card><h2>Host</h2><div class=kv><b>Machine</b><span>$(HE $si.manufacturer) $(HE $si.model)</span><b>Serial</b><span>$(HE $si.serialNumber)</span><b>OS</b><span>$(HE $si.osCaption) (build $(HE $si.osBuild), $(HE $si.osArchitecture))</span><b>CPU</b><span>$(HE $si.cpu) ($($si.cpuCores)C/$($si.cpuLogical)T)</span><b>RAM</b><span>$($si.ramGB) GB</span><b>Domain</b><span>$domTxt</span><b>Uptime</b><span>$(HE $si.uptime)</span><b>Logged-on users</b><span>$userList</span><b>Remote-access / RMM</b><span>$rtxt</span></div><table style='margin-top:12px'><tr><th>Disk</th><th>Size</th><th>Free</th><th>Capacity</th></tr>$diskRows</table></div>"
    }
    $reportName="Incident_Report_$($env:COMPUTERNAME)_$((Get-Date).ToString('yyyyMMdd_HHmmss')).html"
    $reportPath=Join-Path $CaseDir $reportName
    $html="<!DOCTYPE html><html><head><meta charset='utf-8'><title>$BrandName Incident Report</title><style>body{font-family:Segoe UI,Arial,sans-serif;margin:0;background:#f3f4f6;color:#111827}header{background:#0f172a;color:#fff;padding:16px 24px}.wrap{max-width:1000px;margin:20px auto;padding:0 16px}.card{background:#fff;border:1px solid #e5e7eb;border-radius:10px;padding:16px 20px;margin-bottom:16px}.verdict{font-size:24px;font-weight:700;color:$vc}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:7px 9px;border-bottom:1px solid #eef0f3;text-align:left;vertical-align:top}th{background:#f9fafb;font-size:11px;text-transform:uppercase;color:#6b7280}.pill{color:#fff;padding:2px 8px;border-radius:999px;font-size:11px}.note{color:#6b7280;font-size:12px}code{background:#f1f5f9;padding:1px 5px;border-radius:4px}pre{background:#0f172a;color:#e2e8f0;padding:8px;border-radius:6px;overflow:auto;font-size:11px}.kv{display:grid;grid-template-columns:180px 1fr;gap:5px 14px;font-size:14px}</style></head><body><header><h1>$BrandName &middot; Incident Triage Report</h1></header><div class=wrap><div class=card><div class=verdict>$verdict</div><div class=kv><b>Case</b><span>$(HE $caseId)</span><b>Host</b><span>$(HE $env:COMPUTERNAME)</span><b>Classification</b><span>$(HE $classification)</span><b>Severity</b><span>$(HE $maxSev)</span><b>Score</b><span>$score</span><b>Reason</b><span><code>$(HE $reasonCode)</code></span><b>Analyzed (UTC)</b><span>$(HE $result.analyzedTimestampUtc)</span></div></div>$hostCard<div class=card><h2>Detections ($(@($findings).Count))</h2><table><tr><th>Rule</th><th>Finding</th><th>Severity</th><th>Hits</th><th>MITRE</th></tr>$rows</table></div></div><footer style='text-align:center;color:#9ca3af;font-size:12px;padding:18px'>Generated by $BrandName (open source). Deterministic engine - zero network egress.</footer></body></html>"
    Fos-WriteText $html $reportPath
    Fos-CocAdd 'ANALYSIS_DONE' "verdict=$verdict score=$score class=$classification findings=$(@($findings).Count)" @($findingsPath,$reportPath)
    Fos-ManifestNew $caseId

    # ---- console verdict (tech-facing) ----
    if(-not $Quiet){
        $bar=('='*60)
        $vcolor=switch($verdict){'ALL_CLEAR'{'Green'}'MONITOR'{'Yellow'}default{'Red'}}
        Write-Host ""; Write-Host $bar -ForegroundColor $vcolor
        Write-Host ("  {0}  ::  {1}{2}" -f $BrandName.ToUpper(), $verdict, $(if($verdict -eq 'PROBLEM_DETECTED'){" ($classification)"}else{''})) -ForegroundColor $vcolor
        Write-Host ("  HOST: {0}    SCORE: {1}    REASON: {2}" -f $env:COMPUTERNAME,$score,$reasonCode) -ForegroundColor $vcolor
        Write-Host $bar -ForegroundColor $vcolor
        $hi=$bundle.metadata.host
        if($hi){
            $si=$hi.system
            Write-Host "  Machine:" -ForegroundColor Gray
            Write-Host ("   {0} {1}   S/N {2}" -f $si.manufacturer,$si.model,$si.serialNumber) -ForegroundColor DarkGray
            Write-Host ("   OS: {0} (build {1}, {2})" -f $si.osCaption,$si.osBuild,$si.osArchitecture) -ForegroundColor DarkGray
            Write-Host ("   CPU: {0}  ({1}C/{2}T)   RAM: {3} GB   Uptime: {4}" -f $si.cpu,$si.cpuCores,$si.cpuLogical,$si.ramGB,$si.uptime) -ForegroundColor DarkGray
            $dom=if($si.partOfDomain){$si.domain}else{"$($si.domain) (workgroup)"}
            Write-Host ("   Domain: {0}" -f $dom) -ForegroundColor DarkGray
            if(@($hi.disks).Count -gt 0){
                Write-Host "  Disks:" -ForegroundColor Gray
                foreach($dk in $hi.disks){ $lowc=if([double]$dk.percentFree -lt 10){'Red'}elseif([double]$dk.percentFree -lt 20){'Yellow'}else{'DarkGray'}; Write-Host ("   {0}  {1} GB free of {2} GB ({3}% free)" -f $dk.drive,$dk.freeGB,$dk.sizeGB,$dk.percentFree) -ForegroundColor $lowc }
            }
            if(@($hi.loggedOnUsers).Count -gt 0){
                Write-Host "  Logged-on users:" -ForegroundColor Gray
                foreach($u in $hi.loggedOnUsers){ Write-Host ("   {0} ({1})" -f $u.user,$u.session) -ForegroundColor DarkGray }
            } else { Write-Host "  Logged-on users: none detected" -ForegroundColor DarkGray }
            Write-Host $bar -ForegroundColor $vcolor
        }
        if(@($findings).Count -gt 0){
            Write-Host "  Top findings:" -ForegroundColor Gray
            foreach($d in ($findings|Where-Object{$_.weight -gt 0}|Sort-Object -Property @{Expression={$_.weight};Descending=$true}|Select-Object -First 8)){
                Write-Host ("   [{0,-8}] {1}  {2}" -f $d.severity,$d.ruleId,$d.name) -ForegroundColor $(switch($d.severity){'critical'{'Red'}'high'{'Red'}'medium'{'Yellow'}default{'Gray'}})
            }
        }
        $rt=@($bundle.artifacts.remoteAccess.tools)
        if($rt.Count -gt 0){
            Write-Host "  Remote-access / RMM tools (informational - does not affect verdict):" -ForegroundColor Gray
            foreach($t in $rt){ $tag=if($t.authorized){'[expected]  '}else{'[undeclared]'}; Write-Host ("   {0} {1} ({2})" -f $tag,$t.tool,$t.evidence) -ForegroundColor $(if($t.authorized){'DarkGray'}else{'Cyan'}) }
            $undef=@($rt|Where-Object{-not $_.authorized})
            if($undef.Count -gt 0 -and -not $ExpectedRemoteTools){ Write-Host "   (tip: pass -ExpectedRemoteTools 'NinjaOne,ScreenConnect' to label your own agents as expected)" -ForegroundColor DarkGray }
            elseif($undef.Count -gt 0){ Write-Host "   (undeclared = not in your -ExpectedRemoteTools list; confirm each is one you installed)" -ForegroundColor DarkGray }
        }
        $dp=$bundle.artifacts.securityPosture.defender
        if($dp -and $dp.available){ $rtp=if($dp.realTimeEnabled){'on'}else{'OFF'}; $tpp=if($dp.tamperProtectionEnabled){'on'}else{'OFF'}; $exC=(@($dp.exclusionPaths)+@($dp.exclusionExtensions)+@($dp.exclusionProcesses)|Where-Object{$_}).Count; Write-Host ("  Defender: real-time={0}  tamper-protection={1}  exclusions={2}" -f $rtp,$tpp,$exC) -ForegroundColor $(if(-not $dp.realTimeEnabled){'Red'}else{'DarkGray'}) }
        Write-Host $bar -ForegroundColor $vcolor
        Write-Host ("  Report:   {0}" -f $reportPath) -ForegroundColor Gray
        Write-Host ("  Evidence: {0}  (sealed: SHA-256 manifest + chain of custody)" -f $bundlePath) -ForegroundColor Gray
        Write-Host $bar -ForegroundColor $vcolor; Write-Host ""
    }
    Fos-Log "DONE. Verdict=$verdict Score=$score Class=$classification" 'OK'
    exit $exit
}
catch {
    Write-Host "FATAL: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}
