<#
.SYNOPSIS
    Syncs the embedded ruleset inside deploy/standalone/Invoke-FosTriage.ps1 from the
    single source of truth (rules/detections.json).
.DESCRIPTION
    The standalone script is self-contained (one file, no external deps) so it can be pasted
    into an RMM / ScreenConnect run-command window. To avoid rule drift, the engine code lives
    in the standalone but the RULESET is generated from rules/detections.json by this builder.

    Run this whenever you change rules/detections.json:
        .\tools\Build-Standalone.ps1
#>
[CmdletBinding()] param()
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$rulesPath = Join-Path $root 'rules\detections.json'
$standalone = Join-Path $root 'deploy\standalone\Invoke-FosTriage.ps1'

$rulesJson = (Get-Content -LiteralPath $rulesPath -Raw).TrimEnd()
$content = Get-Content -LiteralPath $standalone -Raw

$beginMarker = '# RULES-BEGIN (generated by tools/Build-Standalone.ps1 from rules/detections.json - do not edit by hand)'
$endMarker   = '# RULES-END'
$block = "$beginMarker`r`n`$RULES_JSON = @'`r`n$rulesJson`r`n'@`r`n$endMarker"

$pattern = [regex]::Escape($beginMarker) + '.*?' + [regex]::Escape($endMarker)
$rx = New-Object System.Text.RegularExpressions.Regex($pattern, [System.Text.RegularExpressions.RegexOptions]::Singleline)
if (-not $rx.IsMatch($content)) { throw "Markers not found in $standalone" }
$updated = $rx.Replace($content, [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $block })

$enc = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($standalone, $updated, $enc)
Write-Host "Synced ruleset ($((Get-Content $rulesPath -Raw | ConvertFrom-Json).rules.Count) rules) into $standalone" -ForegroundColor Green
